version: '3.8'

services:
  app:
    build: ./ldap_client/
    container_name: ldap_client
    volumes:
      - ./ldap_client:/app

  web:
    build: ./ldap-frontend/
    container_name: ldap-frontend
    volumes:
      - /app/node_modules
      - ./ldap-frontend:/app

  nginx:
      depends_on:
        - app
        - web
      restart: always
      build: 
        dockerfile: Dockerfile
        context: ./Nginx
      ports:
        - 3050:80